-- Global default settings (admin-editable). Sensitive values stay empty
-- until configured; secrets are stored AES-256-GCM encrypted by the app.
INSERT INTO `settings` (`key`, `value`) VALUES
('app_name', 'Krishna WhatsApp Cloud'),
('app_tagline', 'WhatsApp Business Cloud API Platform'),
('default_language', 'en'),
('default_currency', 'INR'),
('date_format', 'd M Y'),
('assets_version', '1'),
('registration_enabled', '1'),
('email_verification_required', '0'),
('default_plan_slug', 'trial'),
('worker_mode', 'cron'),
('queue_backlog_alert', '5000'),
('alert_email', ''),
('mail_driver', ''),
('mail_host', ''),
('mail_port', '587'),
('mail_encryption', 'tls'),
('mail_username', ''),
('mail_password', ''),
('mail_from_email', ''),
('mail_from_name', ''),
('meta_api_version', 'v21.0'),
('update_github_owner', ''),
('update_github_repo', ''),
('update_github_branch', 'main'),
('update_github_token', ''),
('update_channel', 'branch'),
('update_auto_check', '1'),
('update_auto_install', '0'),
('update_notify_email', ''),
('update_keep_backups', '5'),
('installed_version', '1.0.0'),
('installed_build', '1'),
('installed_commit_sha', ''),
('backup_daily', '0'),
('admin_ip_allowlist', ''),
('captcha_provider', 'math'),
('captcha_site_key', ''),
('captcha_secret', '');
